# Пример k8s конфига (deployment-controller)/ от Merion Academy
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
  # будут запущены 3 пода
  spec:
    replicas: 3
    selector:
      matchLabels:
        app: nginx
      template:
        metadata:
          labels:
            app: nginx
          # каждый из них будет содерж внутри контейнер с nginx
          spec:
            containers:
            - name: nginx
              image: nginx:1.14.2
              ports:
              - containerPort: 80
# еще тут можно описать ENV/перем окружения / порты / лимиты на ресурсы ПК
# то что тут описано и есть "desired state" (к которому будет стремиться/возвращаться k8s)

# Запустить Jaeger (в Docker)
#docker run --rm --name jaeger -p 16686:16686 -p 4317:4317 -p 4318:4318 -p 5778:5778 -p 9411:9411 jaegertracing/jaeger:2.3.0