#name: allure_to.yml / Automated tests
#
#on:
#  # автотест (ЕСЛИ был Push с main ветки ТО самозапуститься Allure (ui для тестов))
#  push:
#  workflow_dispatch:
#    inputs:
#      ALLURE_JOB_RUN_ID:
#      ALLURE_USERNAME:
#
## задаём перем окружения/секр/Настройки Allure
#env:
#  ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
#  ALLURE_JOB_RUN_ID: ${{ github.event.inputs.ALLURE_JOB_RUN_ID }}
#  ALLURE_ENDPOINT: https://seniortester.testops.cloud/
#  ALLURE_PROJECT_ID: 34
#  ALLURE_RESULTS: allure-results
#
#
#permissions:
#  contents: read
#  pages: write
#  id-token: write
#
#jobs:
#
#  test:
#
#    runs-on: ubuntu-latest
#
#    steps:
#      # установим ОС / Python 3.10 / Chrome (нужен для тестов/Selenium) / Allure (ui для тестов)
#      - name: Checkout repository
#        uses: actions/checkout@v3
#      - name: setup Python
#        uses: actions/setup-python@v4
#        with:
#          python-version: "3.10"
#      - name: Install Chrome
#        run: sudo apt-get install google-chrome-stable
#        # установим зависимости / пакеты (из списка requirements.txt)
#      - name: install dependencies
#        run: pip install -r requirements.txt
#        # установим Allure
#      - name: Install allurectl
#        uses: allure-framework/setup-allurectl@v1
#        with:
#          allure-endpoint: https://seniortester.testops.cloud/
#          allure-token: ${{ secrets.ALLURE_TOKEN }}
#          allure-project-id: 34
#
#      # Запустим ВСЕ ТЕСТЫ
#      - name: run all tests
#        # run: echo $ALLURE_PROJECT_ID
#        run: allurectl watch -- pytest --alluredir=allure-results
#        # continue-on-error: true
#        # Сохраняем Рез в файл (чтоб передать в allure)
#      - name: Store allure results
#        uses: actions/upload-artifact@v4
#        with:
#          name: allure-results
#          path:
#            allure-results
#          retention-days: 1  # cleanup: удалим отчёт через 1 день (чтоб не засорять/раздувать git)
#
#
#
